
Lexeme: #include Type: RwInclude Row: 1 Column: 1
Lexeme: header.h Type: LiteralString Row: 1 Column: 9
Lexeme: #include Type: RwInclude Row: 2 Column: 1
Lexeme: Physics/Solver.h Type: LiteralString Row: 2 Column: 9
Lexeme: #include Type: RwInclude Row: 3 Column: 1
Lexeme: < Type: OpLessThan Row: 3 Column: 9
Lexeme: stdio Type: Identifier Row: 3 Column: 10
Lexeme: . Type: Dot Row: 3 Column: 15
Lexeme: h Type: Identifier Row: 3 Column: 16
Lexeme: > Type: OpGreaterThan Row: 3 Column: 17
Lexeme: float Type: RwFloat Row: 5 Column: 0
Lexeme: average Type: Identifier Row: 5 Column: 6
Lexeme: ( Type: OpenParenthesis Row: 5 Column: 14
Lexeme: int Type: RwInt Row: 5 Column: 15
Lexeme: n_args Type: Identifier Row: 5 Column: 19
Lexeme: , Type: Comma Row: 5 Column: 25
Lexeme: . Type: Dot Row: 5 Column: 27
Lexeme: . Type: Dot Row: 5 Column: 28
Lexeme: . Type: Dot Row: 5 Column: 29
Lexeme: ) Type: CloseParenthesis Row: 5 Column: 30
Lexeme: { Type: OpenCurlyBracket Row: 6 Column: 0
Lexeme: char Type: RwChar Row: 7 Column: 4
Lexeme: newline Type: Identifier Row: 7 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 7 Column: 17
Lexeme: \n Type: LiteralChar Row: 7 Column: 19
Lexeme: ; Type: EndOfSentence Row: 7 Column: 23
Lexeme: char Type: RwChar Row: 8 Column: 4
Lexeme: tab Type: Identifier Row: 8 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 8 Column: 13
Lexeme: \t Type: LiteralChar Row: 8 Column: 15
Lexeme: ; Type: EndOfSentence Row: 8 Column: 19
Lexeme: char Type: RwChar Row: 9 Column: 4
Lexeme: backspace Type: Identifier Row: 9 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 9 Column: 19
Lexeme: \b Type: LiteralChar Row: 9 Column: 21
Lexeme: ; Type: EndOfSentence Row: 9 Column: 25
Lexeme: char Type: RwChar Row: 10 Column: 4
Lexeme: backslash Type: Identifier Row: 10 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 10 Column: 19
Lexeme: \\ Type: LiteralChar Row: 10 Column: 21
Lexeme: ; Type: EndOfSentence Row: 10 Column: 25
Lexeme: char Type: RwChar Row: 11 Column: 4
Lexeme: nullChar Type: Identifier Row: 11 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 11 Column: 18
Lexeme: \0 Type: LiteralChar Row: 11 Column: 20
Lexeme: ; Type: EndOfSentence Row: 11 Column: 24
Lexeme: char Type: RwChar Row: 12 Column: 4
Lexeme: quot Type: Identifier Row: 12 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 12 Column: 14
Lexeme: " Type: LiteralChar Row: 12 Column: 16
Lexeme: ; Type: EndOfSentence Row: 12 Column: 19
Lexeme: date Type: RwDate Row: 14 Column: 5
Lexeme: my_date Type: Identifier Row: 14 Column: 10
Lexeme: = Type: OpSimpleAssingment Row: 14 Column: 18
Lexeme: 14-05-1993 Type: LiteralDate Row: 14 Column: 21
Lexeme: ; Type: EndOfSentence Row: 14 Column: 32
Lexeme: var Type: Identifier Row: 15 Column: 5
Lexeme: mistr Type: Identifier Row: 15 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 15 Column: 15
Lexeme: This\nis\na\ntest\n\nShe \"said, \"How are you?\"\n Type: LiteralString Row: 15 Column: 17
Lexeme: ; Type: EndOfSentence Row: 15 Column: 70
Lexeme: va_list Type: Identifier Row: 16 Column: 5
Lexeme: _myList Type: Identifier Row: 16 Column: 13
Lexeme: ; Type: EndOfSentence Row: 16 Column: 20
Lexeme: va_start Type: Identifier Row: 17 Column: 5
Lexeme: ( Type: OpenParenthesis Row: 17 Column: 14
Lexeme: myList Type: Identifier Row: 17 Column: 15
Lexeme: , Type: Comma Row: 17 Column: 21
Lexeme: n_args Type: Identifier Row: 17 Column: 23
Lexeme: ) Type: CloseParenthesis Row: 17 Column: 29
Lexeme: ; Type: EndOfSentence Row: 17 Column: 30
Lexeme: int Type: RwInt Row: 19 Column: 4
Lexeme: numbersAdded Type: Identifier Row: 19 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 19 Column: 21
Lexeme: 3.0 Type: LiteralDecimal Row: 19 Column: 23
Lexeme: ; Type: EndOfSentence Row: 19 Column: 26
Lexeme: int Type: RwInt Row: 20 Column: 4
Lexeme: sum Type: Identifier Row: 20 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 20 Column: 12
Lexeme: 23.45 Type: LiteralDecimal Row: 20 Column: 14
Lexeme: ; Type: EndOfSentence Row: 20 Column: 19
Lexeme: int Type: RwInt Row: 21 Column: 4
Lexeme: hex Type: Identifier Row: 21 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 21 Column: 12
Lexeme: 0x3F7 Type: LiteralHexadecimal Row: 21 Column: 14
Lexeme: ; Type: EndOfSentence Row: 21 Column: 19
Lexeme: int Type: RwInt Row: 22 Column: 4
Lexeme: octal Type: Identifier Row: 22 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 22 Column: 14
Lexeme: 07 Type: LiteralOctal Row: 22 Column: 16
Lexeme: ; Type: EndOfSentence Row: 22 Column: 18
Lexeme: int Type: RwInt Row: 23 Column: 4
Lexeme: number Type: Identifier Row: 23 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 23 Column: 15
Lexeme: 78 Type: LiteralNumber Row: 23 Column: 17
Lexeme: ; Type: EndOfSentence Row: 23 Column: 19
Lexeme: int Type: RwInt Row: 24 Column: 4
Lexeme: n Type: Identifier Row: 24 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 24 Column: 10
Lexeme: 23e10 Type: LiteralFloat Row: 24 Column: 12
Lexeme: ; Type: EndOfSentence Row: 24 Column: 17
Lexeme: int Type: RwInt Row: 25 Column: 4
Lexeme: n2 Type: Identifier Row: 25 Column: 8
Lexeme: = Type: OpSimpleAssingment Row: 25 Column: 11
Lexeme: 23e-5 Type: LiteralFloat Row: 25 Column: 13
Lexeme: ; Type: EndOfSentence Row: 25 Column: 18
Lexeme: while Type: RwWhile Row: 27 Column: 4
Lexeme: ( Type: OpenParenthesis Row: 27 Column: 10
Lexeme: numbersAdded Type: Identifier Row: 27 Column: 11
Lexeme: < Type: OpLessThan Row: 27 Column: 24
Lexeme: n_args Type: Identifier Row: 27 Column: 26
Lexeme: ) Type: CloseParenthesis Row: 27 Column: 32
Lexeme: { Type: OpenCurlyBracket Row: 27 Column: 34
Lexeme: int Type: RwInt Row: 28 Column: 8
Lexeme: number Type: Identifier Row: 28 Column: 12
Lexeme: = Type: OpSimpleAssingment Row: 28 Column: 19
Lexeme: va_arg Type: Identifier Row: 28 Column: 21
Lexeme: ( Type: OpenParenthesis Row: 28 Column: 28
Lexeme: myList Type: Identifier Row: 28 Column: 29
Lexeme: , Type: Comma Row: 28 Column: 35
Lexeme: int Type: RwInt Row: 28 Column: 37
Lexeme: ) Type: CloseParenthesis Row: 28 Column: 40
Lexeme: ; Type: EndOfSentence Row: 28 Column: 41
Lexeme: // Get next number from list Type: LineComment Row: 28 Column: 43
Lexeme: sum Type: Identifier Row: 29 Column: 8
Lexeme: += Type: OpAddAndAssigment Row: 29 Column: 12
Lexeme: number Type: Identifier Row: 29 Column: 15
Lexeme: ; Type: EndOfSentence Row: 29 Column: 21
Lexeme: numbersAdded Type: Identifier Row: 30 Column: 8
Lexeme: += Type: OpAddAndAssigment Row: 30 Column: 21
Lexeme: 1 Type: LiteralNumber Row: 30 Column: 24
Lexeme: ; Type: EndOfSentence Row: 30 Column: 25
Lexeme: } Type: CloseCurlyBracket Row: 31 Column: 4
Lexeme: va_end Type: Identifier Row: 32 Column: 4
Lexeme: ( Type: OpenParenthesis Row: 32 Column: 11
Lexeme: myList Type: Identifier Row: 32 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 32 Column: 18
Lexeme: ; Type: EndOfSentence Row: 32 Column: 19
Lexeme: float Type: RwFloat Row: 34 Column: 4
Lexeme: avg Type: Identifier Row: 34 Column: 10
Lexeme: = Type: OpSimpleAssingment Row: 34 Column: 14
Lexeme: ( Type: OpenParenthesis Row: 34 Column: 16
Lexeme: float Type: RwFloat Row: 34 Column: 17
Lexeme: ) Type: CloseParenthesis Row: 34 Column: 22
Lexeme: ( Type: OpenParenthesis Row: 34 Column: 23
Lexeme: sum Type: Identifier Row: 34 Column: 24
Lexeme: ) Type: CloseParenthesis Row: 34 Column: 27
Lexeme: / Type: OpDivision Row: 34 Column: 29
Lexeme: ( Type: OpenParenthesis Row: 34 Column: 31
Lexeme: float Type: RwFloat Row: 34 Column: 32
Lexeme: ) Type: CloseParenthesis Row: 34 Column: 37
Lexeme: ( Type: OpenParenthesis Row: 34 Column: 38
Lexeme: numbersAdded Type: Identifier Row: 34 Column: 39
Lexeme: ) Type: CloseParenthesis Row: 34 Column: 51
Lexeme: ; Type: EndOfSentence Row: 34 Column: 52
Lexeme: // Find the average Type: LineComment Row: 34 Column: 54
Lexeme: return Type: RwReturn Row: 35 Column: 4
Lexeme: avg Type: Identifier Row: 35 Column: 11
Lexeme: ; Type: EndOfSentence Row: 35 Column: 14
Lexeme: /* my first program in C */ Type: BlockComment Row: 37 Column: 1
Lexeme: printf Type: Identifier Row: 38 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 38 Column: 9
Lexeme: Hello, World! \n Type: LiteralString Row: 38 Column: 10
Lexeme: ) Type: CloseParenthesis Row: 38 Column: 28
Lexeme: ; Type: EndOfSentence Row: 38 Column: 29
Lexeme: char Type: RwChar Row: 39 Column: 3
Lexeme: [ Type: OpenSquareBracket Row: 39 Column: 7
Lexeme: 100 Type: LiteralNumber Row: 39 Column: 8
Lexeme: ] Type: CloseSquareBracket Row: 39 Column: 11
Lexeme: string Type: RwString Row: 39 Column: 13
Lexeme: = Type: OpSimpleAssingment Row: 39 Column: 20
Lexeme: mi cadena Type: LiteralString Row: 39 Column: 22
Lexeme: ; Type: EndOfSentence Row: 39 Column: 33
Lexeme: string Type: RwString Row: 40 Column: 3
Lexeme: mistr Type: Identifier Row: 40 Column: 10
Lexeme: = Type: OpSimpleAssingment Row: 40 Column: 16
Lexeme: mi cadena  Type: LiteralString Row: 40 Column: 19
Lexeme: ; Type: EndOfSentence Row: 40 Column: 31
Lexeme: float Type: RwFloat Row: 41 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 41 Column: 9
Lexeme: a Type: LiteralChar Row: 41 Column: 12
Lexeme: ; Type: EndOfSentence Row: 41 Column: 15
Lexeme: return Type: RwReturn Row: 42 Column: 3
Lexeme: 0 Type: LiteralNumber Row: 42 Column: 10
Lexeme: ; Type: EndOfSentence Row: 42 Column: 11
Lexeme: /*replacement text * Comments blocks like this explain what the following code attemptsreplacement text * to do.  These comments often come directly from the designreplacement text * statement.replacement text */ Type: BlockComment Row: 44 Column: 3
Lexeme: /// <summary> Type: LineComment Row: 50 Column: 0
Lexeme: /// Here is how to use the class: <![CDATA[ <test>Data</test> ]]> Type: LineComment Row: 51 Column: 0
Lexeme: /// </summary> Type: LineComment Row: 52 Column: 0
Lexeme: //"This\nis\na\ntest\n\nShe said, \"How are you?\"\n" Type: LineComment Row: 54 Column: 0
Lexeme: int Type: RwInt Row: 56 Column: 4
Lexeme: x Type: Identifier Row: 56 Column: 8
Lexeme: ; Type: EndOfSentence Row: 56 Column: 9
Lexeme: /* A normal integer*/ Type: BlockComment Row: 56 Column: 22
Lexeme: int Type: RwInt Row: 57 Column: 4
Lexeme: * Type: OpMultiplication Row: 57 Column: 8
Lexeme: p Type: Identifier Row: 57 Column: 9
Lexeme: ; Type: EndOfSentence Row: 57 Column: 10
Lexeme: /* A pointer to an integer ("*p" is an integer, so preplacement text                       must be a pointer to an integer) */ Type: BlockComment Row: 57 Column: 22
Lexeme: p Type: Identifier Row: 59 Column: 4
Lexeme: = Type: OpSimpleAssingment Row: 59 Column: 6
Lexeme: & Type: OpBitAnd Row: 59 Column: 8
Lexeme: x Type: Identifier Row: 59 Column: 9
Lexeme: ; Type: EndOfSentence Row: 59 Column: 10
Lexeme: /* Read it, "assign the address of x to p" */ Type: BlockComment Row: 59 Column: 22
Lexeme: scanf Type: Identifier Row: 60 Column: 4
Lexeme: ( Type: OpenParenthesis Row: 60 Column: 9
Lexeme: %d Type: LiteralString Row: 60 Column: 11
Lexeme: , Type: Comma Row: 60 Column: 15
Lexeme: & Type: OpBitAnd Row: 60 Column: 17
Lexeme: x Type: Identifier Row: 60 Column: 18
Lexeme: ) Type: CloseParenthesis Row: 60 Column: 20
Lexeme: ; Type: EndOfSentence Row: 60 Column: 21
Lexeme: /* Put a value in x, we could also use p here */ Type: BlockComment Row: 60 Column: 32
Lexeme: printf Type: Identifier Row: 61 Column: 4
Lexeme: ( Type: OpenParenthesis Row: 61 Column: 10
Lexeme: %d\n Type: LiteralString Row: 61 Column: 12
Lexeme: , Type: Comma Row: 61 Column: 18
Lexeme: * Type: OpMultiplication Row: 61 Column: 20
Lexeme: p Type: Identifier Row: 61 Column: 21
Lexeme: ) Type: CloseParenthesis Row: 61 Column: 23
Lexeme: ; Type: EndOfSentence Row: 61 Column: 24
Lexeme: /* Note the use of the * to get the value */ Type: BlockComment Row: 61 Column: 26
Lexeme: getchar Type: Identifier Row: 62 Column: 4
Lexeme: ( Type: OpenParenthesis Row: 62 Column: 11
Lexeme: ) Type: CloseParenthesis Row: 62 Column: 12
Lexeme: ; Type: EndOfSentence Row: 62 Column: 13
Lexeme: typedef Type: RwTypedef Row: 63 Column: 4
Lexeme: enum Type: RwEnum Row: 63 Column: 12
Lexeme: { Type: OpenCurlyBracket Row: 63 Column: 17
Lexeme: RANDOM Type: Identifier Row: 63 Column: 18
Lexeme: , Type: Comma Row: 63 Column: 24
Lexeme: IMMEDIATE Type: Identifier Row: 63 Column: 26
Lexeme: , Type: Comma Row: 63 Column: 35
Lexeme: SEARCH Type: Identifier Row: 63 Column: 37
Lexeme: } Type: CloseCurlyBracket Row: 63 Column: 43
Lexeme: strategy Type: Identifier Row: 63 Column: 45
Lexeme: ; Type: EndOfSentence Row: 63 Column: 53
Lexeme: strategy Type: Identifier Row: 64 Column: 4
Lexeme: my_strategy Type: Identifier Row: 64 Column: 13
Lexeme: = Type: OpSimpleAssingment Row: 64 Column: 25
Lexeme: IMMEDIATE Type: Identifier Row: 64 Column: 27
Lexeme: ; Type: EndOfSentence Row: 64 Column: 36
Lexeme: bool Type: RwBool Row: 66 Column: 4
Lexeme: existe Type: Identifier Row: 66 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 66 Column: 16
Lexeme: false Type: RwFalse Row: 66 Column: 18
Lexeme: ; Type: EndOfSentence Row: 66 Column: 23
Lexeme: bool Type: RwBool Row: 67 Column: 4
Lexeme: no_existe Type: Identifier Row: 67 Column: 9
Lexeme: = Type: OpSimpleAssingment Row: 67 Column: 19
Lexeme: true Type: RwTrue Row: 67 Column: 21
Lexeme: ; Type: EndOfSentence Row: 67 Column: 25
Lexeme: } Type: CloseCurlyBracket Row: 68 Column: 0
Lexeme: struct Type: RwStruct Row: 70 Column: 0
Lexeme: Books Type: Identifier Row: 70 Column: 7
Lexeme: { Type: OpenCurlyBracket Row: 70 Column: 13
Lexeme: char Type: RwChar Row: 71 Column: 3
Lexeme: title Type: Identifier Row: 71 Column: 9
Lexeme: [ Type: OpenSquareBracket Row: 71 Column: 14
Lexeme: 50 Type: LiteralNumber Row: 71 Column: 15
Lexeme: ] Type: CloseSquareBracket Row: 71 Column: 17
Lexeme: ; Type: EndOfSentence Row: 71 Column: 18
Lexeme: char Type: RwChar Row: 72 Column: 3
Lexeme: author Type: Identifier Row: 72 Column: 9
Lexeme: [ Type: OpenSquareBracket Row: 72 Column: 15
Lexeme: 50 Type: LiteralNumber Row: 72 Column: 16
Lexeme: ] Type: CloseSquareBracket Row: 72 Column: 18
Lexeme: ; Type: EndOfSentence Row: 72 Column: 19
Lexeme: char Type: RwChar Row: 73 Column: 3
Lexeme: subject Type: Identifier Row: 73 Column: 9
Lexeme: [ Type: OpenSquareBracket Row: 73 Column: 16
Lexeme: 100 Type: LiteralNumber Row: 73 Column: 17
Lexeme: ] Type: CloseSquareBracket Row: 73 Column: 20
Lexeme: ; Type: EndOfSentence Row: 73 Column: 21
Lexeme: int Type: RwInt Row: 74 Column: 3
Lexeme: book_id Type: Identifier Row: 74 Column: 9
Lexeme: ; Type: EndOfSentence Row: 74 Column: 16
Lexeme: } Type: CloseCurlyBracket Row: 75 Column: 0
Lexeme: book Type: Identifier Row: 75 Column: 2
Lexeme: ; Type: EndOfSentence Row: 75 Column: 6
Lexeme: char Type: RwChar Row: 77 Column: 0
Lexeme: greeting Type: Identifier Row: 77 Column: 5
Lexeme: [ Type: OpenSquareBracket Row: 77 Column: 13
Lexeme: 6 Type: LiteralNumber Row: 77 Column: 14
Lexeme: ] Type: CloseSquareBracket Row: 77 Column: 15
Lexeme: = Type: OpSimpleAssingment Row: 77 Column: 17
Lexeme: { Type: OpenCurlyBracket Row: 77 Column: 19
Lexeme: H Type: LiteralChar Row: 77 Column: 20
Lexeme: , Type: Comma Row: 77 Column: 23
Lexeme: e Type: LiteralChar Row: 77 Column: 25
Lexeme: , Type: Comma Row: 77 Column: 28
Lexeme: l Type: LiteralChar Row: 77 Column: 30
Lexeme: , Type: Comma Row: 77 Column: 33
Lexeme: l Type: LiteralChar Row: 77 Column: 35
Lexeme: , Type: Comma Row: 77 Column: 38
Lexeme: o Type: LiteralChar Row: 77 Column: 40
Lexeme: , Type: Comma Row: 77 Column: 43
Lexeme: \0 Type: LiteralChar Row: 77 Column: 45
Lexeme: } Type: CloseCurlyBracket Row: 77 Column: 49
Lexeme: ; Type: EndOfSentence Row: 77 Column: 50
Lexeme: char Type: RwChar Row: 79 Column: 0
Lexeme: _temp Type: Identifier Row: 79 Column: 5
Lexeme: ; Type: EndOfSentence Row: 79 Column: 10
Lexeme: extern Type: RwExtern Row: 81 Column: 0
Lexeme: int Type: RwInt Row: 81 Column: 7
Lexeme: d Type: Identifier Row: 81 Column: 11
Lexeme: = Type: OpSimpleAssingment Row: 81 Column: 13
Lexeme: 3 Type: LiteralNumber Row: 81 Column: 15
Lexeme: , Type: Comma Row: 81 Column: 16
Lexeme: f Type: Identifier Row: 81 Column: 18
Lexeme: = Type: OpSimpleAssingment Row: 81 Column: 20
Lexeme: 5 Type: LiteralNumber Row: 81 Column: 22
Lexeme: ; Type: EndOfSentence Row: 81 Column: 23
Lexeme: // declaration of d and f.  Type: LineComment Row: 81 Column: 28
Lexeme: int Type: RwInt Row: 82 Column: 0
Lexeme: d Type: Identifier Row: 82 Column: 4
Lexeme: = Type: OpSimpleAssingment Row: 82 Column: 6
Lexeme: 3 Type: LiteralNumber Row: 82 Column: 8
Lexeme: , Type: Comma Row: 82 Column: 9
Lexeme: f Type: Identifier Row: 82 Column: 11
Lexeme: = Type: OpSimpleAssingment Row: 82 Column: 13
Lexeme: 5 Type: LiteralNumber Row: 82 Column: 15
Lexeme: ; Type: EndOfSentence Row: 82 Column: 16
Lexeme: // definition and initializing d and f.  Type: LineComment Row: 82 Column: 28
Lexeme: byte Type: Identifier Row: 83 Column: 0
Lexeme: z Type: Identifier Row: 83 Column: 5
Lexeme: = Type: OpSimpleAssingment Row: 83 Column: 7
Lexeme: 22 Type: LiteralNumber Row: 83 Column: 9
Lexeme: ; Type: EndOfSentence Row: 83 Column: 11
Lexeme: // definition and initializes z.  Type: LineComment Row: 83 Column: 28
Lexeme: char Type: RwChar Row: 84 Column: 0
Lexeme: x Type: Identifier Row: 84 Column: 5
Lexeme: = Type: OpSimpleAssingment Row: 84 Column: 7
Lexeme: x Type: LiteralChar Row: 84 Column: 9
Lexeme: ; Type: EndOfSentence Row: 84 Column: 12
Lexeme: // the variable x has the value 'x'. Type: LineComment Row: 84 Column: 28
Lexeme: #include Type: RwInclude Row: 86 Column: 1
Lexeme: < Type: OpLessThan Row: 86 Column: 9
Lexeme: stdio Type: Identifier Row: 86 Column: 10
Lexeme: . Type: Dot Row: 86 Column: 15
Lexeme: h Type: Identifier Row: 86 Column: 16
Lexeme: > Type: OpGreaterThan Row: 86 Column: 17
Lexeme: // Variable declaration: Type: LineComment Row: 88 Column: 0
Lexeme: extern Type: RwExtern Row: 89 Column: 0
Lexeme: int Type: RwInt Row: 89 Column: 7
Lexeme: a Type: Identifier Row: 89 Column: 11
Lexeme: , Type: Comma Row: 89 Column: 12
Lexeme: b Type: Identifier Row: 89 Column: 14
Lexeme: ; Type: EndOfSentence Row: 89 Column: 15
Lexeme: extern Type: RwExtern Row: 90 Column: 0
Lexeme: int Type: RwInt Row: 90 Column: 7
Lexeme: c Type: Identifier Row: 90 Column: 11
Lexeme: ; Type: EndOfSentence Row: 90 Column: 12
Lexeme: extern Type: RwExtern Row: 91 Column: 0
Lexeme: float Type: RwFloat Row: 91 Column: 7
Lexeme: f Type: Identifier Row: 91 Column: 13
Lexeme: ; Type: EndOfSentence Row: 91 Column: 14
Lexeme: int Type: RwInt Row: 93 Column: 0
Lexeme: main Type: Identifier Row: 93 Column: 4
Lexeme: ( Type: OpenParenthesis Row: 93 Column: 9
Lexeme: ) Type: CloseParenthesis Row: 93 Column: 10
Lexeme: { Type: OpenCurlyBracket Row: 93 Column: 12
Lexeme: /* variable definition: */ Type: BlockComment Row: 95 Column: 3
Lexeme: int Type: RwInt Row: 96 Column: 3
Lexeme: a Type: Identifier Row: 96 Column: 7
Lexeme: , Type: Comma Row: 96 Column: 8
Lexeme: b Type: Identifier Row: 96 Column: 10
Lexeme: ; Type: EndOfSentence Row: 96 Column: 11
Lexeme: int Type: RwInt Row: 97 Column: 3
Lexeme: c Type: Identifier Row: 97 Column: 7
Lexeme: ; Type: EndOfSentence Row: 97 Column: 8
Lexeme: float Type: RwFloat Row: 98 Column: 3
Lexeme: f Type: Identifier Row: 98 Column: 9
Lexeme: ; Type: EndOfSentence Row: 98 Column: 10
Lexeme: /* actual initialization */ Type: BlockComment Row: 100 Column: 3
Lexeme: a Type: Identifier Row: 101 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 101 Column: 5
Lexeme: 10 Type: LiteralNumber Row: 101 Column: 7
Lexeme: ; Type: EndOfSentence Row: 101 Column: 9
Lexeme: b Type: Identifier Row: 102 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 102 Column: 5
Lexeme: 20 Type: LiteralNumber Row: 102 Column: 7
Lexeme: ; Type: EndOfSentence Row: 102 Column: 9
Lexeme: c Type: Identifier Row: 104 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 104 Column: 5
Lexeme: a Type: Identifier Row: 104 Column: 7
Lexeme: + Type: OpAdd Row: 104 Column: 9
Lexeme: b Type: Identifier Row: 104 Column: 11
Lexeme: ; Type: EndOfSentence Row: 104 Column: 12
Lexeme: printf Type: Identifier Row: 105 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 105 Column: 9
Lexeme: value of c : %d \n Type: LiteralString Row: 105 Column: 10
Lexeme: , Type: Comma Row: 105 Column: 30
Lexeme: c Type: Identifier Row: 105 Column: 32
Lexeme: ) Type: CloseParenthesis Row: 105 Column: 33
Lexeme: ; Type: EndOfSentence Row: 105 Column: 34
Lexeme: f Type: Identifier Row: 107 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 107 Column: 5
Lexeme: 70.0 Type: LiteralDecimal Row: 107 Column: 7
Lexeme: / Type: OpDivision Row: 107 Column: 11
Lexeme: 3.0 Type: LiteralDecimal Row: 107 Column: 12
Lexeme: ; Type: EndOfSentence Row: 107 Column: 15
Lexeme: printf Type: Identifier Row: 108 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 108 Column: 9
Lexeme: value of f : %f \n Type: LiteralString Row: 108 Column: 10
Lexeme: , Type: Comma Row: 108 Column: 30
Lexeme: f Type: Identifier Row: 108 Column: 32
Lexeme: ) Type: CloseParenthesis Row: 108 Column: 33
Lexeme: ; Type: EndOfSentence Row: 108 Column: 34
Lexeme: return Type: RwReturn Row: 110 Column: 3
Lexeme: 0 Type: LiteralNumber Row: 110 Column: 10
Lexeme: ; Type: EndOfSentence Row: 110 Column: 11
Lexeme: } Type: CloseCurlyBracket Row: 111 Column: 0
Lexeme: int Type: RwInt Row: 113 Column: 2
Lexeme: numbersAdded Type: Identifier Row: 113 Column: 6
Lexeme: = Type: OpSimpleAssingment Row: 113 Column: 19
Lexeme: 3.0 Type: LiteralDecimal Row: 113 Column: 21
Lexeme: ; Type: EndOfSentence Row: 113 Column: 24
Lexeme: int Type: RwInt Row: 115 Column: 2
Lexeme: numbersAdded Type: Identifier Row: 115 Column: 6
Lexeme: = Type: OpSimpleAssingment Row: 115 Column: 19
Lexeme: 3.0 Type: LiteralDecimal Row: 115 Column: 21
Lexeme: ; Type: EndOfSentence Row: 115 Column: 24
Lexeme: int Type: RwInt Row: 115 Column: 28
Lexeme: sum Type: Identifier Row: 115 Column: 32
Lexeme: = Type: OpSimpleAssingment Row: 115 Column: 36
Lexeme: 23.45 Type: LiteralDecimal Row: 115 Column: 38
Lexeme: ; Type: EndOfSentence Row: 115 Column: 43
Lexeme: int Type: RwInt Row: 115 Column: 46
Lexeme: hex Type: Identifier Row: 115 Column: 50
Lexeme: = Type: OpSimpleAssingment Row: 115 Column: 54
Lexeme: 0x3F7 Type: LiteralHexadecimal Row: 115 Column: 56
Lexeme: ; Type: EndOfSentence Row: 115 Column: 61
Lexeme: int Type: RwInt Row: 116 Column: 2
Lexeme: octal Type: Identifier Row: 116 Column: 6
Lexeme: = Type: OpSimpleAssingment Row: 116 Column: 12
Lexeme: 07 Type: LiteralOctal Row: 116 Column: 14
Lexeme: ; Type: EndOfSentence Row: 116 Column: 16
Lexeme: int Type: RwInt Row: 116 Column: 18
Lexeme: number Type: Identifier Row: 116 Column: 22
Lexeme: = Type: OpSimpleAssingment Row: 116 Column: 29
Lexeme: 78 Type: LiteralNumber Row: 116 Column: 31
Lexeme: ; Type: EndOfSentence Row: 116 Column: 33
Lexeme: int Type: RwInt Row: 116 Column: 35
Lexeme: n Type: Identifier Row: 116 Column: 39
Lexeme: = Type: OpSimpleAssingment Row: 116 Column: 41
Lexeme: 23E10 Type: LiteralFloat Row: 116 Column: 43
Lexeme: ; Type: EndOfSentence Row: 116 Column: 48
Lexeme: int Type: RwInt Row: 116 Column: 51
Lexeme: n2 Type: Identifier Row: 116 Column: 55
Lexeme: = Type: OpSimpleAssingment Row: 116 Column: 58
Lexeme: 23e-5 Type: LiteralFloat Row: 116 Column: 60
Lexeme: ; Type: EndOfSentence Row: 116 Column: 65
Lexeme: int Type: RwInt Row: 118 Column: 2
Lexeme: a Type: Identifier Row: 118 Column: 6
Lexeme: = Type: OpSimpleAssingment Row: 118 Column: 8
Lexeme: 5 Type: LiteralNumber Row: 118 Column: 10
Lexeme: ; Type: EndOfSentence Row: 118 Column: 11
Lexeme: int Type: RwInt Row: 119 Column: 3
Lexeme: b Type: Identifier Row: 119 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 119 Column: 9
Lexeme: 20 Type: LiteralNumber Row: 119 Column: 11
Lexeme: ; Type: EndOfSentence Row: 119 Column: 13
Lexeme: int Type: RwInt Row: 120 Column: 3
Lexeme: c Type: Identifier Row: 120 Column: 7
Lexeme: ; Type: EndOfSentence Row: 120 Column: 9
Lexeme: if Type: RwIf Row: 122 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 122 Column: 6
Lexeme: a Type: Identifier Row: 122 Column: 8
Lexeme: && Type: OpAnd Row: 122 Column: 10
Lexeme: b Type: Identifier Row: 122 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 122 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 122 Column: 17
Lexeme: printf Type: Identifier Row: 123 Column: 6
Lexeme: ( Type: OpenParenthesis Row: 123 Column: 12
Lexeme: Line 1 - Condition is true\n Type: LiteralString Row: 123 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 123 Column: 44
Lexeme: ; Type: EndOfSentence Row: 123 Column: 45
Lexeme: } Type: CloseCurlyBracket Row: 124 Column: 3
Lexeme: if Type: RwIf Row: 126 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 126 Column: 6
Lexeme: a Type: Identifier Row: 126 Column: 8
Lexeme: || Type: OpLogicalOr Row: 126 Column: 10
Lexeme: b Type: Identifier Row: 126 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 126 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 126 Column: 17
Lexeme: printf Type: Identifier Row: 127 Column: 6
Lexeme: ( Type: OpenParenthesis Row: 127 Column: 12
Lexeme: Line 2 - Condition is true\n Type: LiteralString Row: 127 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 127 Column: 44
Lexeme: ; Type: EndOfSentence Row: 127 Column: 45
Lexeme: } Type: CloseCurlyBracket Row: 128 Column: 3
Lexeme: /* lets change the value of  a and b */ Type: BlockComment Row: 130 Column: 3
Lexeme: a Type: Identifier Row: 131 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 131 Column: 5
Lexeme: 0 Type: LiteralNumber Row: 131 Column: 7
Lexeme: ; Type: EndOfSentence Row: 131 Column: 8
Lexeme: b Type: Identifier Row: 132 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 132 Column: 5
Lexeme: 10 Type: LiteralNumber Row: 132 Column: 7
Lexeme: ; Type: EndOfSentence Row: 132 Column: 9
Lexeme: if Type: RwIf Row: 134 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 134 Column: 6
Lexeme: a Type: Identifier Row: 134 Column: 8
Lexeme: && Type: OpAnd Row: 134 Column: 10
Lexeme: b Type: Identifier Row: 134 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 134 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 134 Column: 17
Lexeme: printf Type: Identifier Row: 135 Column: 6
Lexeme: ( Type: OpenParenthesis Row: 135 Column: 12
Lexeme: Line 3 - Condition is true\n Type: LiteralString Row: 135 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 135 Column: 44
Lexeme: ; Type: EndOfSentence Row: 135 Column: 45
Lexeme: } Type: CloseCurlyBracket Row: 136 Column: 3
Lexeme: else Type: RwElse Row: 137 Column: 3
Lexeme: { Type: OpenCurlyBracket Row: 137 Column: 8
Lexeme: printf Type: Identifier Row: 138 Column: 6
Lexeme: ( Type: OpenParenthesis Row: 138 Column: 12
Lexeme: Line 3 - Condition is not true\n Type: LiteralString Row: 138 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 138 Column: 48
Lexeme: ; Type: EndOfSentence Row: 138 Column: 49
Lexeme: } Type: CloseCurlyBracket Row: 139 Column: 3
Lexeme: if Type: RwIf Row: 141 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 141 Column: 6
Lexeme: ! Type: OpNot Row: 141 Column: 8
Lexeme: ( Type: OpenParenthesis Row: 141 Column: 9
Lexeme: a Type: Identifier Row: 141 Column: 10
Lexeme: && Type: OpAnd Row: 141 Column: 12
Lexeme: b Type: Identifier Row: 141 Column: 15
Lexeme: ) Type: CloseParenthesis Row: 141 Column: 16
Lexeme: ) Type: CloseParenthesis Row: 141 Column: 18
Lexeme: { Type: OpenCurlyBracket Row: 141 Column: 20
Lexeme: printf Type: Identifier Row: 142 Column: 6
Lexeme: ( Type: OpenParenthesis Row: 142 Column: 12
Lexeme: Line 4 - Condition is true\n Type: LiteralString Row: 142 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 142 Column: 44
Lexeme: ; Type: EndOfSentence Row: 142 Column: 45
Lexeme: } Type: CloseCurlyBracket Row: 143 Column: 3
Lexeme: #include Type: RwInclude Row: 145 Column: 4
Lexeme: < Type: OpLessThan Row: 145 Column: 12
Lexeme: iostream Type: Identifier Row: 145 Column: 13
Lexeme: > Type: OpGreaterThan Row: 145 Column: 21
Lexeme: using Type: Identifier Row: 146 Column: 0
Lexeme: namespace Type: Identifier Row: 146 Column: 6
Lexeme: std Type: Identifier Row: 146 Column: 16
Lexeme: ; Type: EndOfSentence Row: 146 Column: 19
Lexeme: main Type: Identifier Row: 148 Column: 0
Lexeme: ( Type: OpenParenthesis Row: 148 Column: 4
Lexeme: ) Type: CloseParenthesis Row: 148 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 148 Column: 7
Lexeme: int Type: RwInt Row: 149 Column: 3
Lexeme: a Type: Identifier Row: 149 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 149 Column: 9
Lexeme: 21 Type: LiteralNumber Row: 149 Column: 11
Lexeme: ; Type: EndOfSentence Row: 149 Column: 13
Lexeme: int Type: RwInt Row: 150 Column: 3
Lexeme: b Type: Identifier Row: 150 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 150 Column: 9
Lexeme: 10 Type: LiteralNumber Row: 150 Column: 11
Lexeme: ; Type: EndOfSentence Row: 150 Column: 13
Lexeme: int Type: RwInt Row: 151 Column: 3
Lexeme: c Type: Identifier Row: 151 Column: 7
Lexeme: ; Type: EndOfSentence Row: 151 Column: 9
Lexeme: if Type: RwIf Row: 153 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 153 Column: 5
Lexeme: a Type: Identifier Row: 153 Column: 7
Lexeme: == Type: OpEqualTo Row: 153 Column: 9
Lexeme: b Type: Identifier Row: 153 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 153 Column: 14
Lexeme: { Type: OpenCurlyBracket Row: 153 Column: 16
Lexeme: cout Type: Identifier Row: 154 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 154 Column: 11
Lexeme: Line 1 - a is equal to b Type: LiteralString Row: 154 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 154 Column: 41
Lexeme: endl Type: Identifier Row: 154 Column: 44
Lexeme: ; Type: EndOfSentence Row: 154 Column: 49
Lexeme: } Type: CloseCurlyBracket Row: 155 Column: 3
Lexeme: else Type: RwElse Row: 155 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 155 Column: 10
Lexeme: cout Type: Identifier Row: 156 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 156 Column: 11
Lexeme: Line 1 - a is not equal to b Type: LiteralString Row: 156 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 156 Column: 45
Lexeme: endl Type: Identifier Row: 156 Column: 48
Lexeme: ; Type: EndOfSentence Row: 156 Column: 53
Lexeme: } Type: CloseCurlyBracket Row: 157 Column: 3
Lexeme: if Type: RwIf Row: 159 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 159 Column: 6
Lexeme: a Type: Identifier Row: 159 Column: 8
Lexeme: < Type: OpLessThan Row: 159 Column: 10
Lexeme: b Type: Identifier Row: 159 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 159 Column: 14
Lexeme: { Type: OpenCurlyBracket Row: 159 Column: 16
Lexeme: cout Type: Identifier Row: 160 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 160 Column: 11
Lexeme: Line 2 - a is less than b Type: LiteralString Row: 160 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 160 Column: 42
Lexeme: endl Type: Identifier Row: 160 Column: 45
Lexeme: ; Type: EndOfSentence Row: 160 Column: 50
Lexeme: } Type: CloseCurlyBracket Row: 161 Column: 3
Lexeme: else Type: RwElse Row: 161 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 161 Column: 10
Lexeme: cout Type: Identifier Row: 162 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 162 Column: 11
Lexeme: Line 2 - a is not less than b Type: LiteralString Row: 162 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 162 Column: 46
Lexeme: endl Type: Identifier Row: 162 Column: 49
Lexeme: ; Type: EndOfSentence Row: 162 Column: 54
Lexeme: } Type: CloseCurlyBracket Row: 163 Column: 3
Lexeme: if Type: RwIf Row: 165 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 165 Column: 6
Lexeme: a Type: Identifier Row: 165 Column: 8
Lexeme: > Type: OpGreaterThan Row: 165 Column: 10
Lexeme: b Type: Identifier Row: 165 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 165 Column: 14
Lexeme: { Type: OpenCurlyBracket Row: 165 Column: 16
Lexeme: cout Type: Identifier Row: 166 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 166 Column: 11
Lexeme: Line 3 - a is greater than b Type: LiteralString Row: 166 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 166 Column: 45
Lexeme: endl Type: Identifier Row: 166 Column: 48
Lexeme: ; Type: EndOfSentence Row: 166 Column: 53
Lexeme: } Type: CloseCurlyBracket Row: 167 Column: 3
Lexeme: else Type: RwElse Row: 167 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 167 Column: 10
Lexeme: cout Type: Identifier Row: 168 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 168 Column: 11
Lexeme: Line 3 - a is not greater than b Type: LiteralString Row: 168 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 168 Column: 49
Lexeme: endl Type: Identifier Row: 168 Column: 52
Lexeme: ; Type: EndOfSentence Row: 168 Column: 57
Lexeme: } Type: CloseCurlyBracket Row: 169 Column: 3
Lexeme: /* Let's change the values of a and b */ Type: BlockComment Row: 171 Column: 3
Lexeme: a Type: Identifier Row: 172 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 172 Column: 5
Lexeme: 5 Type: LiteralNumber Row: 172 Column: 7
Lexeme: ; Type: EndOfSentence Row: 172 Column: 8
Lexeme: b Type: Identifier Row: 173 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 173 Column: 5
Lexeme: 20 Type: LiteralNumber Row: 173 Column: 7
Lexeme: ; Type: EndOfSentence Row: 173 Column: 9
Lexeme: if Type: RwIf Row: 175 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 175 Column: 6
Lexeme: a Type: Identifier Row: 175 Column: 8
Lexeme: <= Type: OpLessThanOrEqualTo Row: 175 Column: 10
Lexeme: b Type: Identifier Row: 175 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 175 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 175 Column: 17
Lexeme: cout Type: Identifier Row: 176 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 176 Column: 11
Lexeme: Line 4 - a is either less than \replacement text         or euqal to  b Type: LiteralString Row: 176 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 177 Column: 25
Lexeme: endl Type: Identifier Row: 177 Column: 28
Lexeme: ; Type: EndOfSentence Row: 177 Column: 33
Lexeme: } Type: CloseCurlyBracket Row: 178 Column: 3
Lexeme: if Type: RwIf Row: 180 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 180 Column: 6
Lexeme: b Type: Identifier Row: 180 Column: 8
Lexeme: >= Type: OpGreaterThanOrEqualTo Row: 180 Column: 10
Lexeme: a Type: Identifier Row: 180 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 180 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 180 Column: 17
Lexeme: cout Type: Identifier Row: 181 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 181 Column: 11
Lexeme: Line 5 - b is either greater than \replacement text         or equal to b Type: LiteralString Row: 181 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 182 Column: 24
Lexeme: endl Type: Identifier Row: 182 Column: 27
Lexeme: ; Type: EndOfSentence Row: 182 Column: 32
Lexeme: } Type: CloseCurlyBracket Row: 183 Column: 3
Lexeme: return Type: RwReturn Row: 185 Column: 3
Lexeme: 0 Type: LiteralNumber Row: 185 Column: 10
Lexeme: ; Type: EndOfSentence Row: 185 Column: 11
Lexeme: } Type: CloseCurlyBracket Row: 186 Column: 0
Lexeme: #include Type: RwInclude Row: 188 Column: 1
Lexeme: < Type: OpLessThan Row: 188 Column: 9
Lexeme: iostream Type: Identifier Row: 188 Column: 10
Lexeme: > Type: OpGreaterThan Row: 188 Column: 18
Lexeme: using Type: Identifier Row: 189 Column: 0
Lexeme: namespace Type: Identifier Row: 189 Column: 6
Lexeme: std Type: Identifier Row: 189 Column: 16
Lexeme: ; Type: EndOfSentence Row: 189 Column: 19
Lexeme: main Type: Identifier Row: 191 Column: 0
Lexeme: ( Type: OpenParenthesis Row: 191 Column: 4
Lexeme: ) Type: CloseParenthesis Row: 191 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 191 Column: 7
Lexeme: int Type: RwInt Row: 192 Column: 3
Lexeme: a Type: Identifier Row: 192 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 192 Column: 9
Lexeme: 21 Type: LiteralNumber Row: 192 Column: 11
Lexeme: ; Type: EndOfSentence Row: 192 Column: 13
Lexeme: int Type: RwInt Row: 193 Column: 3
Lexeme: b Type: Identifier Row: 193 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 193 Column: 9
Lexeme: 10 Type: LiteralNumber Row: 193 Column: 11
Lexeme: ; Type: EndOfSentence Row: 193 Column: 13
Lexeme: int Type: RwInt Row: 194 Column: 3
Lexeme: c Type: Identifier Row: 194 Column: 7
Lexeme: ; Type: EndOfSentence Row: 194 Column: 9
Lexeme: if Type: RwIf Row: 196 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 196 Column: 5
Lexeme: a Type: Identifier Row: 196 Column: 7
Lexeme: == Type: OpEqualTo Row: 196 Column: 9
Lexeme: b Type: Identifier Row: 196 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 196 Column: 14
Lexeme: { Type: OpenCurlyBracket Row: 196 Column: 16
Lexeme: cout Type: Identifier Row: 197 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 197 Column: 11
Lexeme: Line 1 - a is equal to b Type: LiteralString Row: 197 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 197 Column: 41
Lexeme: endl Type: Identifier Row: 197 Column: 44
Lexeme: ; Type: EndOfSentence Row: 197 Column: 49
Lexeme: } Type: CloseCurlyBracket Row: 198 Column: 3
Lexeme: else Type: RwElse Row: 198 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 198 Column: 10
Lexeme: cout Type: Identifier Row: 199 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 199 Column: 11
Lexeme: Line 1 - a is not equal to b Type: LiteralString Row: 199 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 199 Column: 45
Lexeme: endl Type: Identifier Row: 199 Column: 48
Lexeme: ; Type: EndOfSentence Row: 199 Column: 53
Lexeme: } Type: CloseCurlyBracket Row: 200 Column: 3
Lexeme: if Type: RwIf Row: 202 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 202 Column: 6
Lexeme: a Type: Identifier Row: 202 Column: 8
Lexeme: < Type: OpLessThan Row: 202 Column: 10
Lexeme: b Type: Identifier Row: 202 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 202 Column: 14
Lexeme: { Type: OpenCurlyBracket Row: 202 Column: 16
Lexeme: cout Type: Identifier Row: 203 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 203 Column: 11
Lexeme: Line 2 - a is less than b Type: LiteralString Row: 203 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 203 Column: 42
Lexeme: endl Type: Identifier Row: 203 Column: 45
Lexeme: ; Type: EndOfSentence Row: 203 Column: 50
Lexeme: } Type: CloseCurlyBracket Row: 204 Column: 3
Lexeme: else Type: RwElse Row: 204 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 204 Column: 10
Lexeme: cout Type: Identifier Row: 205 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 205 Column: 11
Lexeme: Line 2 - a is not less than b Type: LiteralString Row: 205 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 205 Column: 46
Lexeme: endl Type: Identifier Row: 205 Column: 49
Lexeme: ; Type: EndOfSentence Row: 205 Column: 54
Lexeme: } Type: CloseCurlyBracket Row: 206 Column: 3
Lexeme: if Type: RwIf Row: 208 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 208 Column: 6
Lexeme: a Type: Identifier Row: 208 Column: 8
Lexeme: > Type: OpGreaterThan Row: 208 Column: 10
Lexeme: b Type: Identifier Row: 208 Column: 12
Lexeme: ) Type: CloseParenthesis Row: 208 Column: 14
Lexeme: { Type: OpenCurlyBracket Row: 208 Column: 16
Lexeme: cout Type: Identifier Row: 209 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 209 Column: 11
Lexeme: Line 3 - a is greater than b Type: LiteralString Row: 209 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 209 Column: 45
Lexeme: endl Type: Identifier Row: 209 Column: 48
Lexeme: ; Type: EndOfSentence Row: 209 Column: 53
Lexeme: } Type: CloseCurlyBracket Row: 210 Column: 3
Lexeme: else Type: RwElse Row: 210 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 210 Column: 10
Lexeme: cout Type: Identifier Row: 211 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 211 Column: 11
Lexeme: Line 3 - a is not greater than b Type: LiteralString Row: 211 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 211 Column: 49
Lexeme: endl Type: Identifier Row: 211 Column: 52
Lexeme: ; Type: EndOfSentence Row: 211 Column: 57
Lexeme: } Type: CloseCurlyBracket Row: 212 Column: 3
Lexeme: /* Let's change the values of a and b */ Type: BlockComment Row: 214 Column: 3
Lexeme: a Type: Identifier Row: 215 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 215 Column: 5
Lexeme: 5 Type: LiteralNumber Row: 215 Column: 7
Lexeme: ; Type: EndOfSentence Row: 215 Column: 8
Lexeme: b Type: Identifier Row: 216 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 216 Column: 5
Lexeme: 20 Type: LiteralNumber Row: 216 Column: 7
Lexeme: ; Type: EndOfSentence Row: 216 Column: 9
Lexeme: if Type: RwIf Row: 218 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 218 Column: 6
Lexeme: a Type: Identifier Row: 218 Column: 8
Lexeme: <= Type: OpLessThanOrEqualTo Row: 218 Column: 10
Lexeme: b Type: Identifier Row: 218 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 218 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 218 Column: 17
Lexeme: cout Type: Identifier Row: 219 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 219 Column: 11
Lexeme: Line 4 - a is either less than \replacement text         or euqal to  b Type: LiteralString Row: 219 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 220 Column: 25
Lexeme: endl Type: Identifier Row: 220 Column: 28
Lexeme: ; Type: EndOfSentence Row: 220 Column: 33
Lexeme: } Type: CloseCurlyBracket Row: 221 Column: 3
Lexeme: if Type: RwIf Row: 223 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 223 Column: 6
Lexeme: b Type: Identifier Row: 223 Column: 8
Lexeme: >= Type: OpGreaterThanOrEqualTo Row: 223 Column: 10
Lexeme: a Type: Identifier Row: 223 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 223 Column: 15
Lexeme: { Type: OpenCurlyBracket Row: 223 Column: 17
Lexeme: cout Type: Identifier Row: 224 Column: 6
Lexeme: << Type: OpBitShiftLeft Row: 224 Column: 11
Lexeme: Line 5 - b is either greater than \replacement text         or equal to b Type: LiteralString Row: 224 Column: 14
Lexeme: << Type: OpBitShiftLeft Row: 225 Column: 24
Lexeme: endl Type: Identifier Row: 225 Column: 27
Lexeme: ; Type: EndOfSentence Row: 225 Column: 32
Lexeme: } Type: CloseCurlyBracket Row: 226 Column: 3
Lexeme: string Type: RwString Row: 228 Column: 3
Lexeme: mi_str Type: Identifier Row: 228 Column: 10
Lexeme: = Type: OpSimpleAssingment Row: 228 Column: 17
Lexeme: prueba\replacement text   dos Type: LiteralString Row: 228 Column: 19
Lexeme: ; Type: EndOfSentence Row: 229 Column: 7
Lexeme: return Type: RwReturn Row: 231 Column: 3
Lexeme: 0 Type: LiteralNumber Row: 231 Column: 10
Lexeme: ; Type: EndOfSentence Row: 231 Column: 11
Lexeme: } Type: CloseCurlyBracket Row: 232 Column: 0
Lexeme: #include Type: RwInclude Row: 234 Column: 1
Lexeme: < Type: OpLessThan Row: 234 Column: 9
Lexeme: iostream Type: Identifier Row: 234 Column: 10
Lexeme: > Type: OpGreaterThan Row: 234 Column: 18
Lexeme: using Type: Identifier Row: 235 Column: 0
Lexeme: namespace Type: Identifier Row: 235 Column: 6
Lexeme: std Type: Identifier Row: 235 Column: 16
Lexeme: ; Type: EndOfSentence Row: 235 Column: 19
Lexeme: main Type: Identifier Row: 237 Column: 0
Lexeme: ( Type: OpenParenthesis Row: 237 Column: 4
Lexeme: ) Type: CloseParenthesis Row: 237 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 237 Column: 7
Lexeme: unsigned Type: RwUnsigned Row: 238 Column: 3
Lexeme: int Type: RwInt Row: 238 Column: 12
Lexeme: a Type: Identifier Row: 238 Column: 16
Lexeme: = Type: OpSimpleAssingment Row: 238 Column: 18
Lexeme: 60 Type: LiteralNumber Row: 238 Column: 20
Lexeme: ; Type: EndOfSentence Row: 238 Column: 22
Lexeme: // 60 = 0011 1100   Type: LineComment Row: 238 Column: 26
Lexeme: unsigned Type: RwUnsigned Row: 239 Column: 3
Lexeme: int Type: RwInt Row: 239 Column: 12
Lexeme: b Type: Identifier Row: 239 Column: 16
Lexeme: = Type: OpSimpleAssingment Row: 239 Column: 18
Lexeme: 13 Type: LiteralNumber Row: 239 Column: 20
Lexeme: ; Type: EndOfSentence Row: 239 Column: 22
Lexeme: // 13 = 0000 1101 Type: LineComment Row: 239 Column: 26
Lexeme: int Type: RwInt Row: 240 Column: 3
Lexeme: c Type: Identifier Row: 240 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 240 Column: 9
Lexeme: 0 Type: LiteralNumber Row: 240 Column: 11
Lexeme: ; Type: EndOfSentence Row: 240 Column: 12
Lexeme: c Type: Identifier Row: 242 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 242 Column: 5
Lexeme: a Type: Identifier Row: 242 Column: 7
Lexeme: & Type: OpBitAnd Row: 242 Column: 9
Lexeme: b Type: Identifier Row: 242 Column: 11
Lexeme: ; Type: EndOfSentence Row: 242 Column: 12
Lexeme: // 12 = 0000 1100 Type: LineComment Row: 242 Column: 26
Lexeme: cout Type: Identifier Row: 243 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 243 Column: 8
Lexeme: Line 1 - Value of c is :  Type: LiteralString Row: 243 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 243 Column: 39
Lexeme: c Type: Identifier Row: 243 Column: 42
Lexeme: << Type: OpBitShiftLeft Row: 243 Column: 44
Lexeme: endl Type: Identifier Row: 243 Column: 47
Lexeme: ; Type: EndOfSentence Row: 243 Column: 52
Lexeme: c Type: Identifier Row: 245 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 245 Column: 5
Lexeme: a Type: Identifier Row: 245 Column: 7
Lexeme: | Type: OpBitOr Row: 245 Column: 9
Lexeme: b Type: Identifier Row: 245 Column: 11
Lexeme: ; Type: EndOfSentence Row: 245 Column: 12
Lexeme: // 61 = 0011 1101 Type: LineComment Row: 245 Column: 26
Lexeme: cout Type: Identifier Row: 246 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 246 Column: 8
Lexeme: Line 2 - Value of c is:  Type: LiteralString Row: 246 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 246 Column: 38
Lexeme: c Type: Identifier Row: 246 Column: 41
Lexeme: << Type: OpBitShiftLeft Row: 246 Column: 43
Lexeme: endl Type: Identifier Row: 246 Column: 46
Lexeme: ; Type: EndOfSentence Row: 246 Column: 51
Lexeme: c Type: Identifier Row: 248 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 248 Column: 5
Lexeme: a Type: Identifier Row: 248 Column: 7
Lexeme: ^ Type: OpBitXor Row: 248 Column: 9
Lexeme: b Type: Identifier Row: 248 Column: 11
Lexeme: ; Type: EndOfSentence Row: 248 Column: 12
Lexeme: // 49 = 0011 0001 Type: LineComment Row: 248 Column: 26
Lexeme: cout Type: Identifier Row: 249 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 249 Column: 8
Lexeme: Line 3 - Value of c is:  Type: LiteralString Row: 249 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 249 Column: 38
Lexeme: c Type: Identifier Row: 249 Column: 41
Lexeme: << Type: OpBitShiftLeft Row: 249 Column: 43
Lexeme: endl Type: Identifier Row: 249 Column: 46
Lexeme: ; Type: EndOfSentence Row: 249 Column: 51
Lexeme: c Type: Identifier Row: 251 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 251 Column: 5
Lexeme: ~ Type: OpComplement Row: 251 Column: 7
Lexeme: a Type: Identifier Row: 251 Column: 8
Lexeme: ; Type: EndOfSentence Row: 251 Column: 9
Lexeme: // -61 = 1100 0011 Type: LineComment Row: 251 Column: 26
Lexeme: cout Type: Identifier Row: 252 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 252 Column: 8
Lexeme: Line 4 - Value of c is:  Type: LiteralString Row: 252 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 252 Column: 38
Lexeme: c Type: Identifier Row: 252 Column: 41
Lexeme: << Type: OpBitShiftLeft Row: 252 Column: 43
Lexeme: endl Type: Identifier Row: 252 Column: 46
Lexeme: ; Type: EndOfSentence Row: 252 Column: 51
Lexeme: c Type: Identifier Row: 254 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 254 Column: 5
Lexeme: a Type: Identifier Row: 254 Column: 7
Lexeme: << Type: OpBitShiftLeft Row: 254 Column: 9
Lexeme: 2 Type: LiteralNumber Row: 254 Column: 12
Lexeme: ; Type: EndOfSentence Row: 254 Column: 13
Lexeme: // 240 = 1111 0000 Type: LineComment Row: 254 Column: 26
Lexeme: cout Type: Identifier Row: 255 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 255 Column: 8
Lexeme: Line 5 - Value of c is:  Type: LiteralString Row: 255 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 255 Column: 38
Lexeme: c Type: Identifier Row: 255 Column: 41
Lexeme: << Type: OpBitShiftLeft Row: 255 Column: 43
Lexeme: endl Type: Identifier Row: 255 Column: 46
Lexeme: ; Type: EndOfSentence Row: 255 Column: 51
Lexeme: c Type: Identifier Row: 257 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 257 Column: 5
Lexeme: a Type: Identifier Row: 257 Column: 7
Lexeme: >> Type: OpBitShiftRight Row: 257 Column: 9
Lexeme: 2 Type: LiteralNumber Row: 257 Column: 12
Lexeme: ; Type: EndOfSentence Row: 257 Column: 13
Lexeme: // 15 = 0000 1111 Type: LineComment Row: 257 Column: 26
Lexeme: cout Type: Identifier Row: 258 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 258 Column: 8
Lexeme: Line 6 - Value of c is:  Type: LiteralString Row: 258 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 258 Column: 38
Lexeme: c Type: Identifier Row: 258 Column: 41
Lexeme: << Type: OpBitShiftLeft Row: 258 Column: 43
Lexeme: endl Type: Identifier Row: 258 Column: 46
Lexeme: ; Type: EndOfSentence Row: 258 Column: 51
Lexeme: return Type: RwReturn Row: 260 Column: 3
Lexeme: 0 Type: LiteralNumber Row: 260 Column: 10
Lexeme: ; Type: EndOfSentence Row: 260 Column: 11
Lexeme: } Type: CloseCurlyBracket Row: 261 Column: 0
Lexeme: #include Type: RwInclude Row: 264 Column: 1
Lexeme: < Type: OpLessThan Row: 264 Column: 9
Lexeme: iostream Type: Identifier Row: 264 Column: 10
Lexeme: > Type: OpGreaterThan Row: 264 Column: 18
Lexeme: using Type: Identifier Row: 265 Column: 0
Lexeme: namespace Type: Identifier Row: 265 Column: 6
Lexeme: std Type: Identifier Row: 265 Column: 16
Lexeme: ; Type: EndOfSentence Row: 265 Column: 19
Lexeme: main Type: Identifier Row: 267 Column: 0
Lexeme: ( Type: OpenParenthesis Row: 267 Column: 4
Lexeme: ) Type: CloseParenthesis Row: 267 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 267 Column: 7
Lexeme: int Type: RwInt Row: 268 Column: 3
Lexeme: a Type: Identifier Row: 268 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 268 Column: 9
Lexeme: 21 Type: LiteralNumber Row: 268 Column: 11
Lexeme: ; Type: EndOfSentence Row: 268 Column: 13
Lexeme: int Type: RwInt Row: 269 Column: 3
Lexeme: c Type: Identifier Row: 269 Column: 7
Lexeme: ; Type: EndOfSentence Row: 269 Column: 9
Lexeme: c Type: Identifier Row: 271 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 271 Column: 5
Lexeme: a Type: Identifier Row: 271 Column: 8
Lexeme: ; Type: EndOfSentence Row: 271 Column: 9
Lexeme: cout Type: Identifier Row: 272 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 272 Column: 8
Lexeme: Line 1 - =  Operator, Value of c = :  Type: LiteralString Row: 272 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 272 Column: 51
Lexeme: c Type: Identifier Row: 272 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 272 Column: 54
Lexeme: endl Type: Identifier Row: 272 Column: 57
Lexeme: ; Type: EndOfSentence Row: 272 Column: 62
Lexeme: c Type: Identifier Row: 274 Column: 3
Lexeme: += Type: OpAddAndAssigment Row: 274 Column: 5
Lexeme: a Type: Identifier Row: 274 Column: 9
Lexeme: ; Type: EndOfSentence Row: 274 Column: 10
Lexeme: cout Type: Identifier Row: 275 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 275 Column: 8
Lexeme: Line 2 - += Operator, Value of c = :  Type: LiteralString Row: 275 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 275 Column: 51
Lexeme: c Type: Identifier Row: 275 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 275 Column: 54
Lexeme: endl Type: Identifier Row: 275 Column: 57
Lexeme: ; Type: EndOfSentence Row: 275 Column: 62
Lexeme: c Type: Identifier Row: 277 Column: 3
Lexeme: -= Type: OpSusbtractAndAssignment Row: 277 Column: 5
Lexeme: a Type: Identifier Row: 277 Column: 9
Lexeme: ; Type: EndOfSentence Row: 277 Column: 10
Lexeme: cout Type: Identifier Row: 278 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 278 Column: 8
Lexeme: Line 3 - -= Operator, Value of c = :  Type: LiteralString Row: 278 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 278 Column: 51
Lexeme: c Type: Identifier Row: 278 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 278 Column: 54
Lexeme: endl Type: Identifier Row: 278 Column: 57
Lexeme: ; Type: EndOfSentence Row: 278 Column: 62
Lexeme: c Type: Identifier Row: 280 Column: 3
Lexeme: *= Type: OpMultiplyAndAssignment Row: 280 Column: 5
Lexeme: a Type: Identifier Row: 280 Column: 9
Lexeme: ; Type: EndOfSentence Row: 280 Column: 10
Lexeme: cout Type: Identifier Row: 281 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 281 Column: 8
Lexeme: Line 4 - *= Operator, Value of c = :  Type: LiteralString Row: 281 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 281 Column: 51
Lexeme: c Type: Identifier Row: 281 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 281 Column: 54
Lexeme: endl Type: Identifier Row: 281 Column: 57
Lexeme: ; Type: EndOfSentence Row: 281 Column: 62
Lexeme: c Type: Identifier Row: 283 Column: 3
Lexeme: /= Type: OpDivideAssignment Row: 283 Column: 5
Lexeme: a Type: Identifier Row: 283 Column: 9
Lexeme: ; Type: EndOfSentence Row: 283 Column: 10
Lexeme: cout Type: Identifier Row: 284 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 284 Column: 8
Lexeme: Line 5 - /= Operator, Value of c = :  Type: LiteralString Row: 284 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 284 Column: 51
Lexeme: c Type: Identifier Row: 284 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 284 Column: 54
Lexeme: endl Type: Identifier Row: 284 Column: 57
Lexeme: ; Type: EndOfSentence Row: 284 Column: 62
Lexeme: c Type: Identifier Row: 286 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 286 Column: 6
Lexeme: 200 Type: LiteralNumber Row: 286 Column: 8
Lexeme: ; Type: EndOfSentence Row: 286 Column: 11
Lexeme: c Type: Identifier Row: 287 Column: 3
Lexeme: %= Type: OpModulusAssignment Row: 287 Column: 5
Lexeme: a Type: Identifier Row: 287 Column: 9
Lexeme: ; Type: EndOfSentence Row: 287 Column: 10
Lexeme: cout Type: Identifier Row: 288 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 288 Column: 8
Lexeme: Line 6 - %= Operator, Value of c = :  Type: LiteralString Row: 288 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 288 Column: 51
Lexeme: c Type: Identifier Row: 288 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 288 Column: 54
Lexeme: endl Type: Identifier Row: 288 Column: 57
Lexeme: ; Type: EndOfSentence Row: 288 Column: 62
Lexeme: c Type: Identifier Row: 290 Column: 3
Lexeme: <<= Type: OpBitShiftLeftAndAssignment Row: 290 Column: 5
Lexeme: = Type: OpSimpleAssingment Row: 290 Column: 7
Lexeme: 2 Type: LiteralNumber Row: 290 Column: 10
Lexeme: ; Type: EndOfSentence Row: 290 Column: 11
Lexeme: cout Type: Identifier Row: 291 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 291 Column: 8
Lexeme: Line 7 - <<= Operator, Value of c = :  Type: LiteralString Row: 291 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 291 Column: 52
Lexeme: c Type: Identifier Row: 291 Column: 54
Lexeme: << Type: OpBitShiftLeft Row: 291 Column: 55
Lexeme: endl Type: Identifier Row: 291 Column: 58
Lexeme: ; Type: EndOfSentence Row: 291 Column: 63
Lexeme: c Type: Identifier Row: 293 Column: 3
Lexeme: >>= Type: OpBitShiftRightAndAssignment Row: 293 Column: 5
Lexeme: = Type: OpSimpleAssingment Row: 293 Column: 7
Lexeme: 2 Type: LiteralNumber Row: 293 Column: 10
Lexeme: ; Type: EndOfSentence Row: 293 Column: 11
Lexeme: cout Type: Identifier Row: 294 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 294 Column: 8
Lexeme: Line 8 - >>= Operator, Value of c = :  Type: LiteralString Row: 294 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 294 Column: 52
Lexeme: c Type: Identifier Row: 294 Column: 54
Lexeme: << Type: OpBitShiftLeft Row: 294 Column: 55
Lexeme: endl Type: Identifier Row: 294 Column: 58
Lexeme: ; Type: EndOfSentence Row: 294 Column: 63
Lexeme: c Type: Identifier Row: 296 Column: 3
Lexeme: &= Type: OpBitwiseAndAssignment Row: 296 Column: 5
Lexeme: 2 Type: LiteralNumber Row: 296 Column: 9
Lexeme: ; Type: EndOfSentence Row: 296 Column: 10
Lexeme: cout Type: Identifier Row: 297 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 297 Column: 8
Lexeme: Line 9 - &= Operator, Value of c = :  Type: LiteralString Row: 297 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 297 Column: 51
Lexeme: c Type: Identifier Row: 297 Column: 53
Lexeme: << Type: OpBitShiftLeft Row: 297 Column: 54
Lexeme: endl Type: Identifier Row: 297 Column: 57
Lexeme: ; Type: EndOfSentence Row: 297 Column: 62
Lexeme: c Type: Identifier Row: 299 Column: 3
Lexeme: ^= Type: OpBitwiseXorAndAssingment Row: 299 Column: 5
Lexeme: 2 Type: LiteralNumber Row: 299 Column: 9
Lexeme: ; Type: EndOfSentence Row: 299 Column: 10
Lexeme: cout Type: Identifier Row: 300 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 300 Column: 8
Lexeme: Line 10 - ^= Operator, Value of c = :  Type: LiteralString Row: 300 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 300 Column: 52
Lexeme: c Type: Identifier Row: 300 Column: 54
Lexeme: << Type: OpBitShiftLeft Row: 300 Column: 55
Lexeme: endl Type: Identifier Row: 300 Column: 58
Lexeme: ; Type: EndOfSentence Row: 300 Column: 63
Lexeme: c Type: Identifier Row: 302 Column: 3
Lexeme: |= Type: OpBitwiseInclusiveOrAndAssigment Row: 302 Column: 5
Lexeme: 2 Type: LiteralNumber Row: 302 Column: 9
Lexeme: ; Type: EndOfSentence Row: 302 Column: 10
Lexeme: cout Type: Identifier Row: 303 Column: 3
Lexeme: << Type: OpBitShiftLeft Row: 303 Column: 8
Lexeme: Line 11 - |= Operator, Value of c = :  Type: LiteralString Row: 303 Column: 11
Lexeme: << Type: OpBitShiftLeft Row: 303 Column: 52
Lexeme: c Type: Identifier Row: 303 Column: 54
Lexeme: << Type: OpBitShiftLeft Row: 303 Column: 55
Lexeme: endl Type: Identifier Row: 303 Column: 58
Lexeme: ; Type: EndOfSentence Row: 303 Column: 63
Lexeme: return Type: RwReturn Row: 305 Column: 3
Lexeme: 0 Type: LiteralNumber Row: 305 Column: 10
Lexeme: ; Type: EndOfSentence Row: 305 Column: 11
Lexeme: } Type: CloseCurlyBracket Row: 306 Column: 0
Lexeme: #include Type: RwInclude Row: 308 Column: 1
Lexeme: < Type: OpLessThan Row: 308 Column: 9
Lexeme: stdio Type: Identifier Row: 308 Column: 10
Lexeme: . Type: Dot Row: 308 Column: 15
Lexeme: h Type: Identifier Row: 308 Column: 16
Lexeme: > Type: OpGreaterThan Row: 308 Column: 17
Lexeme: main Type: Identifier Row: 310 Column: 0
Lexeme: ( Type: OpenParenthesis Row: 310 Column: 4
Lexeme: ) Type: CloseParenthesis Row: 310 Column: 5
Lexeme: { Type: OpenCurlyBracket Row: 310 Column: 7
Lexeme: int Type: RwInt Row: 312 Column: 3
Lexeme: a Type: Identifier Row: 312 Column: 7
Lexeme: = Type: OpSimpleAssingment Row: 312 Column: 9
Lexeme: 4 Type: LiteralNumber Row: 312 Column: 11
Lexeme: ; Type: EndOfSentence Row: 312 Column: 12
Lexeme: short Type: RwShort Row: 313 Column: 3
Lexeme: b Type: Identifier Row: 313 Column: 9
Lexeme: ; Type: EndOfSentence Row: 313 Column: 10
Lexeme: double Type: RwDouble Row: 314 Column: 3
Lexeme: c Type: Identifier Row: 314 Column: 10
Lexeme: ; Type: EndOfSentence Row: 314 Column: 11
Lexeme: int Type: RwInt Row: 315 Column: 3
Lexeme: * Type: OpMultiplication Row: 315 Column: 6
Lexeme: ptr Type: Identifier Row: 315 Column: 8
Lexeme: ; Type: EndOfSentence Row: 315 Column: 11
Lexeme: /* example of sizeof operator */ Type: BlockComment Row: 317 Column: 3
Lexeme: printf Type: Identifier Row: 318 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 318 Column: 9
Lexeme: Line 1 - Size of variable a = %d\n Type: LiteralString Row: 318 Column: 10
Lexeme: , Type: Comma Row: 318 Column: 46
Lexeme: sizeof Type: RwSizeOf Row: 318 Column: 48
Lexeme: ( Type: OpenParenthesis Row: 318 Column: 54
Lexeme: a Type: Identifier Row: 318 Column: 55
Lexeme: ) Type: CloseParenthesis Row: 318 Column: 56
Lexeme: ) Type: CloseParenthesis Row: 318 Column: 58
Lexeme: ; Type: EndOfSentence Row: 318 Column: 59
Lexeme: printf Type: Identifier Row: 319 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 319 Column: 9
Lexeme: Line 2 - Size of variable b = %d\n Type: LiteralString Row: 319 Column: 10
Lexeme: , Type: Comma Row: 319 Column: 46
Lexeme: sizeof Type: RwSizeOf Row: 319 Column: 48
Lexeme: ( Type: OpenParenthesis Row: 319 Column: 54
Lexeme: b Type: Identifier Row: 319 Column: 55
Lexeme: ) Type: CloseParenthesis Row: 319 Column: 56
Lexeme: ) Type: CloseParenthesis Row: 319 Column: 58
Lexeme: ; Type: EndOfSentence Row: 319 Column: 59
Lexeme: printf Type: Identifier Row: 320 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 320 Column: 9
Lexeme: Line 3 - Size of variable c= %d\n Type: LiteralString Row: 320 Column: 10
Lexeme: , Type: Comma Row: 320 Column: 45
Lexeme: sizeof Type: RwSizeOf Row: 320 Column: 47
Lexeme: ( Type: OpenParenthesis Row: 320 Column: 53
Lexeme: c Type: Identifier Row: 320 Column: 54
Lexeme: ) Type: CloseParenthesis Row: 320 Column: 55
Lexeme: ) Type: CloseParenthesis Row: 320 Column: 57
Lexeme: ; Type: EndOfSentence Row: 320 Column: 58
Lexeme: /* example of & and * operators */ Type: BlockComment Row: 322 Column: 3
Lexeme: ptr Type: Identifier Row: 323 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 323 Column: 7
Lexeme: & Type: OpBitAnd Row: 323 Column: 9
Lexeme: a Type: Identifier Row: 323 Column: 10
Lexeme: ; Type: EndOfSentence Row: 323 Column: 11
Lexeme: /* 'ptr' now contains the address of 'a'*/ Type: BlockComment Row: 323 Column: 13
Lexeme: printf Type: Identifier Row: 324 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 324 Column: 9
Lexeme: value of a is  %d\n Type: LiteralString Row: 324 Column: 10
Lexeme: , Type: Comma Row: 324 Column: 31
Lexeme: a Type: Identifier Row: 324 Column: 33
Lexeme: ) Type: CloseParenthesis Row: 324 Column: 34
Lexeme: ; Type: EndOfSentence Row: 324 Column: 35
Lexeme: printf Type: Identifier Row: 325 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 325 Column: 9
Lexeme: *ptr is %d.\n Type: LiteralString Row: 325 Column: 10
Lexeme: , Type: Comma Row: 325 Column: 25
Lexeme: * Type: OpMultiplication Row: 325 Column: 27
Lexeme: ptr Type: Identifier Row: 325 Column: 28
Lexeme: ) Type: CloseParenthesis Row: 325 Column: 31
Lexeme: ; Type: EndOfSentence Row: 325 Column: 32
Lexeme: /* example of ternary operator */ Type: BlockComment Row: 327 Column: 3
Lexeme: a Type: Identifier Row: 328 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 328 Column: 5
Lexeme: 10 Type: LiteralNumber Row: 328 Column: 7
Lexeme: ; Type: EndOfSentence Row: 328 Column: 9
Lexeme: b Type: Identifier Row: 329 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 329 Column: 5
Lexeme: ( Type: OpenParenthesis Row: 329 Column: 7
Lexeme: a Type: Identifier Row: 329 Column: 8
Lexeme: == Type: OpEqualTo Row: 329 Column: 10
Lexeme: 1 Type: LiteralNumber Row: 329 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 329 Column: 14
Lexeme: ? Type: ConditionalExpression Row: 329 Column: 16
Lexeme: 20 Type: LiteralNumber Row: 329 Column: 18
Lexeme: : Type: Colon Row: 329 Column: 20
Lexeme: 30 Type: LiteralNumber Row: 329 Column: 22
Lexeme: ; Type: EndOfSentence Row: 329 Column: 24
Lexeme: printf Type: Identifier Row: 330 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 330 Column: 9
Lexeme: Value of b is %d\n Type: LiteralString Row: 330 Column: 11
Lexeme: , Type: Comma Row: 330 Column: 31
Lexeme: b Type: Identifier Row: 330 Column: 33
Lexeme: ) Type: CloseParenthesis Row: 330 Column: 35
Lexeme: ; Type: EndOfSentence Row: 330 Column: 36
Lexeme: b Type: Identifier Row: 332 Column: 3
Lexeme: = Type: OpSimpleAssingment Row: 332 Column: 5
Lexeme: ( Type: OpenParenthesis Row: 332 Column: 7
Lexeme: a Type: Identifier Row: 332 Column: 8
Lexeme: == Type: OpEqualTo Row: 332 Column: 10
Lexeme: 10 Type: LiteralNumber Row: 332 Column: 13
Lexeme: ) Type: CloseParenthesis Row: 332 Column: 15
Lexeme: ? Type: ConditionalExpression Row: 332 Column: 17
Lexeme: 20 Type: LiteralNumber Row: 332 Column: 19
Lexeme: : Type: Colon Row: 332 Column: 21
Lexeme: 30 Type: LiteralNumber Row: 332 Column: 23
Lexeme: ; Type: EndOfSentence Row: 332 Column: 25
Lexeme: printf Type: Identifier Row: 333 Column: 3
Lexeme: ( Type: OpenParenthesis Row: 333 Column: 9
Lexeme: Value of b is %d\n Type: LiteralString Row: 333 Column: 11
Lexeme: , Type: Comma Row: 333 Column: 31
Lexeme: b Type: Identifier Row: 333 Column: 33
Lexeme: ) Type: CloseParenthesis Row: 333 Column: 35
Lexeme: ; Type: EndOfSentence Row: 333 Column: 36
Lexeme: } Type: CloseCurlyBracket Row: 334 Column: 0